name: Crash Report
description: Report a crash with the modpack
title: "[Crash]: "
labels: [ crash ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
        
  - type: input
    id: modpack-version
    attributes:
      label: Modpack Version
      placeholder: E.g. 1.0.2-hf1
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Issue Description"
      
  - type: textarea
    id: description
    attributes:
      label: When did this crash occur?
      placeholder: E.g. 'Preparing to Create a World'
    validations:
      required: true
    
  - type: input
    id: logs
    attributes:
      label: Crash Log(s)
      description: Please upload a link to your crash report
    validations:
      required: true
